Repository nimblehq/flutter-ic-david-bruce, pull requests merged in 2023-04, with the labels that each got.

#38 [#6] [UI] As a User, I can see Splash screen
  android/app/build.gradle
  android/app/src/main/kotlin/co/nimblehq/flutter/template/MainActivity.kt
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/mipmap/launch_image.png
  android/app/src/main/res/mipmap/white_logo.png
  ios/Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/Contents.json
  ios/Runner/Assets.xcassets/background-image.imageset/Contents.json
  ios/Runner/Assets.xcassets/background-image.imageset/splash-screen-background-image.pdf
  ios/Runner/Assets.xcassets/logo-white-icon.imageset/Contents.json
  ios/Runner/Assets.xcassets/logo-white-icon.imageset/logo-white-icon.pdf
  ios/Runner/Base.lproj/LaunchScreen.storyboard
  ios/fastlane/Constants/Constants.rb
  lib/env.dart
  scripts/setup.py
  scripts/test.py
Labels: type : feature, @0.1.0

#39 [#4] [Chore] Set up CI/CD with Github Actions
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  .github/workflows/deploy_android_production.yml
  .github/workflows/deploy_android_staging.yml
  .github/workflows/deploy_ios_production.yml
  .github/workflows/deploy_ios_staging.yml
  .github/workflows/ios_deploy_to_app_store.yml
  .github/workflows/ios_deploy_to_testflight.yml
  .github/workflows/lint_and_test.yml
  .github/workflows/test.yml
  android/app/build.gradle
  ios/Flutter/AppFrameworkInfo.plist
  ios/Gemfile.lock
  ios/fastlane/Constants/Constants.rb
  ios/fastlane/Constants/Environments.rb
  ios/fastlane/Fastfile
Labels: type : chore, @0.1.0

#43 Release - 0.1.0
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  .github/workflows/deploy_android_production.yml
  .github/workflows/deploy_android_staging.yml
  .github/workflows/deploy_ios_production.yml
  .github/workflows/deploy_ios_staging.yml
  .github/workflows/ios_deploy_to_app_store.yml
  .github/workflows/ios_deploy_to_testflight.yml
  .github/workflows/lint_and_test.yml
  .github/workflows/test.yml
  android/app/build.gradle
  android/app/src/main/kotlin/co/nimblehq/flutter/template/MainActivity.kt
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/mipmap/launch_image.png
  android/app/src/main/res/mipmap/white_logo.png
  ios/Flutter/AppFrameworkInfo.plist
  ios/Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/Contents.json
  ios/Runner/Assets.xcassets/background-image.imageset/Contents.json
  ios/Runner/Assets.xcassets/background-image.imageset/splash-screen-background-image.pdf
  ios/Runner/Assets.xcassets/logo-white-icon.imageset/Contents.json
  ios/Runner/Assets.xcassets/logo-white-icon.imageset/logo-white-icon.pdf
  ios/Runner/Base.lproj/LaunchScreen.storyboard
  ios/fastlane/Constants/Constants.rb
  ios/fastlane/Constants/Environments.rb
  ios/fastlane/Fastfile
  lib/env.dart
  scripts/setup.py
  scripts/test.py
Labels: type : feature

#44 [Chore] Bump application to version 0.2.0
  pubspec.yaml
Labels: type : chore

#45 [#7] [UI] As a user, I can sign in with email and password
  assets/images/bg_login_overlay.png
  assets/images/ic_nimble_white_logo.png
  lib/generated/assets.dart
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/main.dart
  lib/ui/login/login_screen.dart
  lib/ui/widget/input_field_widget.dart
  lib/utils/context_ext.dart
  lib/utils/dimension.dart
Labels: type : feature, @0.2.0

#46 [#11] [UI] As a user, I can reset my password
  integration_test/my_home_page_test.dart
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/main.dart
  lib/ui/forgot_password/forgot_password_screen.dart
  lib/ui/login/login_screen.dart
  lib/utils/custom_app_bar.dart
  lib/utils/themes.dart
Labels: type : feature, @0.2.0

#47 [#21] [UI] As a user, I can see error alert
  lib/utils/context_ext.dart
Labels: type : feature, @0.2.0

#49 Release - 0.2.0
  assets/images/bg_login_overlay.png
  assets/images/ic_nimble_white_logo.png
  integration_test/my_home_page_test.dart
  lib/generated/assets.dart
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/main.dart
  lib/ui/forgot_password/forgot_password_screen.dart
  lib/ui/login/login_screen.dart
  lib/ui/widget/input_field_widget.dart
  lib/utils/context_ext.dart
  lib/utils/custom_app_bar.dart
  lib/utils/dimension.dart
  lib/utils/themes.dart
  pubspec.yaml
Labels: type : release, @0.2.0

#50 Bump version to 0.3.0
  pubspec.yaml
Labels: type : chore, @0.3.0

#48 [#8] [#10] [Chore] [Backend] Setup API Service & As a user, I can login
  lib/api/api_service.dart
  lib/api/auth_api_service.dart
  lib/api/repository/auth_repository.dart
  lib/api/repository/credential_repository.dart
  lib/api/storage/storage.dart
  lib/di/di.dart
  lib/di/interceptor/app_interceptor.dart
  lib/di/module/network_module.dart
  lib/di/module/storage_module.dart
  lib/di/provider/dio_provider.dart
  lib/main.dart
  lib/model/login_model.dart
  lib/model/request/login_request.dart
  lib/model/response/converter/response_converter.dart
  lib/model/response/login_response.dart
  lib/model/response/user_response.dart
  lib/usecases/login_use_case.dart
  lib/usecases/params/login_params.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/auth_repository_test.dart
  test/api/repository/credential_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/login_use_case_test.dart
Labels: type : chore, type : feature, @0.2.0

#51 [#12] [Backend] As a user, I can reset password
  android/app/build.gradle
  lib/api/auth_api_service.dart
  lib/api/repository/auth_repository.dart
  lib/model/forgot_password_model.dart
  lib/model/request/forgot_password_request.dart
  lib/model/request/forgot_password_user_request.dart
  lib/model/response/forgot_password_response.dart
  lib/usecases/forgot_password_use_case.dart
  test/api/repository/auth_repository_test.dart
  test/usecases/forgot_password_use_case_test.dart
Labels: type : feature, @0.3.0

#53 Release - 0.3.0
  android/app/build.gradle
  lib/api/api_service.dart
  lib/api/auth_api_service.dart
  lib/api/repository/auth_repository.dart
  lib/api/repository/credential_repository.dart
  lib/api/storage/storage.dart
  lib/di/di.dart
  lib/di/interceptor/app_interceptor.dart
  lib/di/module/network_module.dart
  lib/di/module/storage_module.dart
  lib/di/provider/dio_provider.dart
  lib/main.dart
  lib/model/forgot_password_model.dart
  lib/model/login_model.dart
  lib/model/request/forgot_password_request.dart
  lib/model/request/forgot_password_user_request.dart
  lib/model/request/login_request.dart
  lib/model/response/converter/response_converter.dart
  lib/model/response/forgot_password_response.dart
  lib/model/response/login_response.dart
  lib/model/response/user_response.dart
  lib/usecases/forgot_password_use_case.dart
  lib/usecases/login_use_case.dart
  lib/usecases/params/login_params.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/auth_repository_test.dart
  test/api/repository/credential_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/forgot_password_use_case_test.dart
  test/usecases/login_use_case_test.dart
Labels: type : release, @0.3.0

#52 [#9] [Integration] As a user, I can sign in
  ios/Podfile.lock
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/main.dart
  lib/ui/home/home_screen.dart
  lib/ui/login/login_screen.dart
  lib/ui/login/login_state.dart
  lib/ui/login/login_view_model.dart
  lib/ui/widget/input_field_widget.dart
  lib/ui/widget/loading_dialog.dart
  lib/utils/context_ext.dart
  lib/utils/route_path.dart
  lib/utils/string_ext.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/viewmodel/login_view_model_test.dart
Labels: type : feature, @0.3.0, @0.4.0

#54 [#13] [Integrate] As a user, I can reset my password
  lib/api/repository/auth_repository.dart
  lib/model/forgot_password_model.dart
  lib/model/response/converter/response_converter.dart
  lib/model/response/forgot_password_meta_response.dart
  lib/model/response/forgot_password_response.dart
  lib/ui/forgot_password/forgot_password_screen.dart
  lib/ui/forgot_password/forgot_password_state.dart
  lib/ui/forgot_password/forgot_password_view_model.dart
  lib/usecases/forgot_password_use_case.dart
  test/api/repository/auth_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/forgot_password_use_case_test.dart
  test/viewmodel/forgot_password_view_model_test.dart
Labels: type : feature, @0.4.0

#55 [#22] [Integration] As a user, when access token expired, application must automatically refresh it
  integration_test/utils/test_util.dart
  lib/api/auth_api_service.dart
  lib/api/repository/auth_repository.dart
  lib/di/interceptor/app_interceptor.dart
  lib/main.dart
  lib/model/refresh_token_model.dart
  lib/model/request/login_request.dart
  lib/model/request/refresh_token_request.dart
  lib/model/response/refresh_token_response.dart
  lib/ui/forgot_password/forgot_password_screen.dart
  lib/usecases/login_use_case.dart
  lib/usecases/refresh_token_use_case.dart
  lib/utils/app_route.dart
  lib/utils/route_path.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/usecases/login_use_case_test.dart
  test/usecases/refresh_token_use_case_test.dart
Labels: type : feature, @0.4.0

#56 [#16] [Backend] As a signed-in user, I can see Home Screen
  lib/api/repository/auth_repository.dart
  lib/api/repository/survey_repository.dart
  lib/api/service/api_service.dart
  lib/api/service/auth_api_service.dart
  lib/di/module/network_module.dart
  lib/model/response/converter/response_converter.dart
  lib/model/response/survey_response.dart
  lib/model/response/surveys_meta_response.dart
  lib/model/response/surveys_response.dart
  lib/model/survey_meta_model.dart
  lib/model/survey_model.dart
  lib/model/surveys_model.dart
  lib/ui/login/login_view_model.dart
  lib/usecases/get_surveys_use_case.dart
  lib/usecases/params/surveys_params.dart
  test/api/repository/survey_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/get_surveys_use_case_test.dart
  test/viewmodel/login_view_model_test.dart
Labels: type : feature, @0.4.0

#59 [#24] [Backend] As a user, I can see Survey Detail Questions Screen
  lib/api/repository/survey_repository.dart
  lib/api/service/api_service.dart
  lib/model/enum/display_type.dart
  lib/model/enum/emoticon_type.dart
  lib/model/response/survey_answer_response.dart
  lib/model/response/survey_question_response.dart
  lib/model/response/survey_response.dart
  lib/model/survey_answer_model.dart
  lib/model/survey_model.dart
  lib/model/survey_question_model.dart
  lib/usecases/get_survey_details_use_case.dart
  test/usecases/get_survey_details_use_case_test.dart
Labels: type : feature, @0.4.0

#57 [#34] [UI] As a signed-in user, I can see the User Menu on the right home Home Screen when tap the avatar
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/ui/home/home_screen.dart
  lib/ui/home/home_side_menu.dart
  lib/ui/home/home_side_menu_ui_model.dart
Labels: type : feature, @0.4.0
