Repository nimblehq/flutter-ic-david-bruce, pull requests merged in 2023-05, with the labels that each got.

#64 [Chore] Bump version to 1.0.0
  pubspec.yaml
Labels: type : chore

#62 [#14] [UI] As a user, I can see the Home loading screen
  lib/ui/home/home_screen.dart
  lib/ui/home/loading/home_loading.dart
  lib/ui/home/loading/home_loading_text.dart
  lib/utils/app_route.dart
  lib/utils/dimension.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, @0.4.0, @0.5.0

#58 [#15] [UI] As a signed-in user, I can see the Home Screen
  ios/Podfile.lock
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/ui/home/home_footer_widget.dart
  lib/ui/home/home_header_widget.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_state.dart
  lib/ui/home/home_view_model.dart
  lib/ui/home/loading/home_loading.dart
  lib/ui/login/login_screen.dart
  lib/utils/app_route.dart
  lib/utils/date_formatter.dart
  lib/utils/dimension.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, @0.4.0, @1.0.0

#67 [#25] [UI] As a user, I can submit survey's answers
  assets/json/submit_successfully.json
  ios/Podfile.lock
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/ui/forgot_password/forgot_password_screen.dart
  lib/ui/login/login_screen.dart
  lib/ui/widgets/input_field_widget.dart
  lib/ui/widgets/loading_dialog.dart
  lib/ui/widgets/lottie_dialog.dart
  lib/utils/context_ext.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, @1.0.0

#66 [#19] [#20] [UI] [Integrate] As a user, I can see Survey Detail Questions Screen
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/model/response/survey_answer_response.dart
  lib/model/response/survey_question_response.dart
  lib/model/survey_model.dart
  lib/ui/forgot_password/forgot_password_screen.dart
  lib/ui/home/home_footer_widget.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/loading/home_skeleton_loading.dart
  lib/ui/login/login_screen.dart
  lib/ui/survey_details/survey_details_component_id.dart
  lib/ui/survey_details/survey_details_screen.dart
  lib/ui/survey_details/survey_details_skeleton_loading.dart
  lib/ui/survey_details/survey_details_state.dart
  lib/ui/survey_details/survey_details_ui_model.dart
  lib/ui/survey_details/survey_details_view_model.dart
  lib/utils/app_route.dart
  lib/utils/dimension.dart
  lib/utils/loading_text.dart
  lib/utils/route_path.dart
  test/mocks/generate_mocks.dart
  test/viewmodel/survey_details_view_model_test.dart
Labels: @1.0.0

#65 [#17] [#18] [Integration] PART 1 - As a signed-in user, I can see horizontal scrollable list of survey and pull down to refresh survey list on the Home screen
  lib/ui/home/home_footer_widget.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_view_model.dart
Labels: type : feature, @0.4.0, @1.0.0

#71 [#23] [UI] As a user, when tap on close button while in middle of answering survey question, I must see warning alert confirm
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/ui/survey_question/survey_question_views/survey_question_view.dart
Labels: type : feature, @1.0.0

#68 [#17] [#18] [Integration] PART 2 - As a signed-in user, I can see horizontal scrollable list of survey and pull down to refresh survey list on the Home screen
  lib/api/repository/survey_repository.dart
  lib/api/storage/storage.dart
  lib/model/survey_meta_model.dart
  lib/model/surveys_model.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_view_model.dart
  lib/usecases/fetch_surveys_use_case.dart
  lib/usecases/get_surveys_cached_use_case.dart
  lib/usecases/login_use_case.dart
  lib/usecases/save_surveys_use_case.dart
  test/api/repository/survey_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/fetch_surveys_use_case_test.dart
  test/usecases/save_surveys_use_case_test.dart
Labels: type : feature, @0.3.0, @0.4.0, @1.0.0

#72 [#29] [#30] [#32] [UI] [UI] As a user, I can see Multiple Choice, Emoticon, Text Field Form Question
  lib/ui/survey_details/survey_details_screen.dart
  lib/ui/survey_question/survey_answer_views/emoticon_view.dart
  lib/ui/survey_question/survey_answer_views/multiple_choice_view.dart
  lib/ui/survey_question/survey_answer_views/single_choice_view.dart
  lib/ui/survey_question/survey_answer_views/survey_answer_component_id.dart
  lib/ui/survey_question/survey_answer_views/text_field_form_view.dart
  lib/ui/survey_question/survey_questions_screen_builder.dart
  lib/ui/survey_question/ui_models/multiple_choice_option_ui_model.dart
  lib/utils/dimension.dart
Labels: type : feature, @1.0.0

#74 [#28] [UI] As a user, I can see Thumbs Up, Heart, Star Survey Question
  lib/model/survey_model.dart
  lib/ui/home/home_screen.dart
  lib/ui/survey_details/survey_details_screen.dart
  lib/ui/survey_question/survey_answer_views/emoticon_view.dart
  lib/ui/survey_question/survey_question_views/survey_question_view.dart
  lib/ui/survey_question/survey_questions_screen.dart
  lib/ui/survey_question/survey_questions_state.dart
  lib/ui/survey_question/survey_questions_view_model.dart
  lib/utils/custom_app_bar.dart
  test/viewmodel/survey_questions_view_model_test.dart
Labels: type : feature, @1.0.0

#75 [#31] [UI] As a user, I can see Point Rating Survey Question
  ios/Podfile.lock
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/ui/survey_question/survey_answer_views/point_rating_view.dart
  lib/ui/survey_question/survey_questions_screen_builder.dart
Labels: type : feature, @1.0.0

#76 [#33] [UI] As a user, I can see Thought Sharing Survey Question
  lib/model/response/survey_answer_response.dart
  lib/model/response/survey_question_response.dart
  lib/model/survey_answer_model.dart
  lib/ui/survey_question/survey_answer_views/input_decoration.dart
  lib/ui/survey_question/survey_answer_views/text_area_form_view.dart
  lib/ui/survey_question/survey_answer_views/text_field_form_view.dart
  lib/ui/survey_question/survey_questions_screen_builder.dart
  lib/ui/survey_question/survey_questions_view_model.dart
  lib/ui/survey_question/ui_models/survey_answer_option_ui_model.dart
  test/viewmodel/survey_questions_view_model_test.dart
Labels: type : feature, @1.0.0

#73 [#36] [Integration] As a user, I can see Survey Detail Questions Screen
  ios/Podfile.lock
  lib/api/repository/survey_repository.dart
  lib/ui/survey_question/survey_questions_screen.dart
  lib/ui/survey_question/survey_questions_screen_builder.dart
  lib/ui/survey_question/survey_questions_view_model.dart
  lib/usecases/base/base_use_case.dart
  lib/usecases/base/use_case_result.dart
  lib/usecases/get_survey_submission_use_case.dart
  lib/usecases/save_current_survey_use_case.dart
  lib/usecases/save_survey_submission_use_case.dart
  test/api/repository/survey_repository_test.dart
  test/mocks/generate_mocks.dart
  test/viewmodel/survey_questions_view_model_test.dart
Labels: type : feature, @1.0.0

#77 [#35] [Integration] As a user, I can submit survey's answers
  lib/ui/survey_question/survey_questions_screen.dart
  lib/ui/survey_question/survey_questions_view_model.dart
  test/mocks/generate_mocks.dart
  test/viewmodel/survey_questions_view_model_test.dart
Labels: type : feature, @1.0.0

#84 [#81] [#82] [UI [Integration] As a user, I can see the profile information on home screen and on right sideba
  lib/api/repository/user_repository.dart
  lib/api/service/api_service.dart
  lib/model/response/user_response.dart
  lib/model/user_model.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_view_model.dart
  lib/usecases/get_user_profile_use_case.dart
  test/api/repository/user_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/get_user_profile_use_case_test.dart
Labels: type : feature, @1.0.0

#85 [#83] [Integration] As a user, I can logout the application
  lib/api/repository/auth_repository.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_side_menu.dart
  lib/ui/home/home_view_model.dart
  lib/usecases/logout_use_case.dart
  test/api/repository/auth_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/logout_use_case_test.dart
Labels: type : feature, @1.0.0

#86 [#78] [Chore] As a developer, I can run UI test with the logging in flow
  integration_test/fake_services/fake_api_service.dart
  integration_test/fake_services/fake_auth_api_service.dart
  integration_test/login_test.dart
  integration_test/real_app_test.dart
  integration_test/utils/fake_data.dart
  integration_test/utils/test_util.dart
  integration_test_fake_data/forget_password.json
  integration_test_fake_data/me.json
  integration_test_fake_data/oauth_login.json
  integration_test_fake_data/refresh_token.json
  integration_test_fake_data/survey_detail.json
  integration_test_fake_data/surveys.json
  lib/ui/login/login_component_id.dart
  lib/ui/login/login_screen.dart
  lib/utils/durations.dart
  lib/utils/file_util.dart
  pubspec.yaml
Labels: type : chore, @1.0.0

#87 [#79] [Chore] As a developer, I can run UI test with the logging out flow
  integration_test/home_test.dart
  lib/ui/home/home_footer_component_id.dart
  lib/ui/home/home_footer_widget.dart
  lib/ui/home/home_side_menu.dart
  lib/ui/home/home_side_menu_component_id.dart
Labels: type : chore, @1.0.0

#88 [#80] [Chore] As a developer, I can run UI test with a completing survey flow
  integration_test/home_test.dart
  integration_test/survey_details_test.dart
  integration_test/survey_questions_test.dart
  integration_test_fake_data/survey_detail.json
  integration_test_fake_data/surveys.json
  lib/ui/survey_details/survey_details_view_model.dart
  lib/utils/route_path.dart
Labels: type : chore, @1.0.0, @1.0.1

#90 Release - 1.0.1
  integration_test/home_test.dart
  integration_test/survey_details_test.dart
  integration_test/survey_questions_test.dart
  integration_test_fake_data/survey_detail.json
  integration_test_fake_data/surveys.json
  lib/ui/survey_details/survey_details_view_model.dart
  lib/utils/route_path.dart
Labels: type : release, @1.0.1
